apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-app-backend
          image: tarunkoshti/notes-kubernetes-test:latest
          # To switch from using a remote image to a local image for deployment,
          # comment out the 'image:' line that specifies the remote image,
          # and uncomment the 'image:' line that specifies the local image.
          # Comment out the image: line above and uncomment the one below to use a local image
          # image: localhost:4000/notes-kubernetes-test:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: kubernetes
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb+srv://<mongo_user>:<mongo_password>@<mongo_host/notes-app-typescript"
